version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: subscription-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: subscription_db
      MYSQL_USER: postgres      # You can keep 'postgres' as the username, but 'root' is MySQL default
      MYSQL_PASSWORD: postgres
      MYSQL_ROOT_PASSWORD: postgres
      TZ: Asia/Kolkata
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      # MySQL uses mysqladmin for healthchecks
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppostgres"]
      interval: 5s
      timeout: 5s
      retries: 5

      flyway:
    enabled: true
    baseline-on-migrate: true
    repair-on-migrate: true  
    locations: classpath:db/migration
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

volumes:
  mysqldata:
